# Generated by Django 6.0.6 on 2026-06-03 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("descripcion", models.TextField()),
                ("duracion_horas", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=2, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Taller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("descripcion", models.TextField()),
                ("instrucciones", models.TextField()),
                ("duracion_dias", models.PositiveIntegerField(default=7)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("teoria", "Teoría"),
                            ("video", "Video"),
                            ("ejercicio", "Ejercicio"),
                            ("quiz", "Quiz"),
                            ("taller", "Taller"),
                        ],
                        default="teoria",
                        max_length=20,
                    ),
                ),
                ("contenido_html", models.TextField(blank=True)),
                ("url_video", models.URLField(blank=True)),
                ("duracion_minutos", models.PositiveIntegerField(default=30)),
                ("puntos", models.PositiveIntegerField(default=10)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecciones",
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                ("respuesta_correcta", models.TextField()),
                ("explicacion", models.TextField(blank=True)),
                ("puntos", models.PositiveIntegerField(default=5)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "leccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ejercicios",
                        to="cursos.leccion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostica", "Diagnóstica"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                        ],
                        default="formativa",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("tiempo_limite", models.PositiveIntegerField(default=60)),
                ("puntaje_maximo", models.PositiveIntegerField(default=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "nivel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones",
                        to="cursos.nivel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curso",
            name="nivel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="cursos.nivel",
            ),
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("multiple", "Opción Múltiple"),
                            ("verdadero_falso", "Verdadero/Falso"),
                            ("texto", "Texto Libre"),
                        ],
                        default="multiple",
                        max_length=20,
                    ),
                ),
                ("puntos", models.PositiveIntegerField(default=5)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="cursos.evaluacion",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="cursos.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgresoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("puntaje", models.PositiveIntegerField(default=0)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
                    ),
                ),
                (
                    "leccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.leccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progreso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "curso", "leccion")},
            },
        ),
        migrations.CreateModel(
            name="TallerEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha_entrega", models.DateTimeField(auto_now_add=True)),
                ("calificacion", models.PositiveIntegerField(default=0)),
                ("comentario_profesor", models.TextField(blank=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="cursos.taller",
                    ),
                ),
            ],
            options={
                "unique_together": {("taller", "estudiante")},
            },
        ),
    ]
